export const types = {
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  IS_LOADING: 'IS_LOADING',
  SET_ERROR: 'SET_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  CLEAR_MESSAGE: 'CLEAR_MESSAGE',
  GET_TRANSACTIONS_BY_USER: 'GET_TRANSACTIONS_BY_USER',
  DEPOSE_SUCCESS: 'DEPOSE_SUCCESS',
  WITHDRAW_SUCCESS: 'WITHDRAW_SUCCESS',
};
